spring:
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:sponsored-ads-db;mode=mysql"
    username: "sponsored-ads-service"
    password: "J3gfOpi94ShWmAOC3a6FFiles6s"
    driver-class-name: "org.h2.Driver"
  flyway:
    baseline-version: 1.0.0.00
    baseline-on-migrate: true
    baseline-description: sponsored-ads-db version 1.0.0.00
    url: "jdbc:h2:mem:sponsored-ads-db;mode=mysql"
    user: "sponsored-ads-service"
    password: "J3gfOpi94ShWmAOC3a6FFiles6s"
    installed-by: Avi Kurt
    enabled: true
    schemas: sponsored-ads-db
    placeholders:
      schema_name: sponsored-ads-db
    locations: classpath:/flyway/db-migration
    create-schemas: true
    driver-class-name: "org.h2.Driver"
