server:
  port: 8080
  shutdown: "graceful"

campaign:
  duration-in-days: 10

spring:
  application:
    name: sponsored-ads
  main:
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: "60s"
  datasource:
    url: "jdbc:mysql://localhost/sponsored-ads-db"
    username: "root"
    password: "root"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  flyway:
    baseline-version: 1.0.0.00
    baseline-on-migrate: true
    baseline-description: sponsored-ads-db version 1.0.0.00
    url: "jdbc:mysql://localhost"
    user: "root"
    password: "root"
    installed-by: Avi Kurt
    enabled: true
    schemas: sponsored-ads-db
    placeholders:
      schema_name: sponsored-ads-db
    locations: classpath:/flyway/db-migration
    create-schemas: true
    driver-class-name: com.mysql.cj.jdbc.Driver
