management:
  server:
    port: 8081
    base-path: /criteo/api/v1/management
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    filter: true
    displayOperationId: true
  use-management-port: true
  show-actuator: true
