spring:
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:sponsored-ads-db;mode=mysql"
    driver-class-name: "org.h2.Driver"
  flyway:
    url: "jdbc:h2:mem:sponsored-ads-db;mode=mysql"
    driver-class-name: "org.h2.Driver"
